# Basics
baseURL: https://fachinformatikerpruefungsvorbereitung.de
title: Fachinformatiker Prüfungsvorbereitung
enableGitInfo: true

# Modules
module:
  imports:
    - path: github.com/Fedodo/Fedodo.Docs.Theme
    - path: github.com/google/docsy/dependencies

# Content
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: tango

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango

params:
  features:
    analytics:
      enabled: true
      goatCounter:
        code: fipv
  links:
    user:
      - name: "GitHub"
        url: "https://github.com/Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung"
        icon: "fab fa-github"
  description: "Fachinformatiker Prüfungsvorbereitung ist eine Seite zur Prüfungsvorbereitung. Mit dieser Seite kannst du dich einfach auf die Fachinformatiker Prüfung vorbereiten."
  copyright: "The Fachinformatiker-Prüfungsvorbereitung Authors"
  ui:
    readingTime:
      enable: true

  offlineSearch: true
  algolia_docsearch: false
  offlineSearchSummaryLength: 70
  offlineSearchMaxResults: 10
  prism_syntax_highlighting: false

  # GitHub
  github_repo: "https://github.com/Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung"
  github_project_repo: "https://github.com/Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung"
  github_branch: "dev"

  mermaid:
    enable: false
    theme: default
  plantuml:
    enable: false
    theme: default
    svg_image_url: https://www.plantuml.com/plantuml/svg/
    svg: false
  katex:
    enable: false
    html_dom_element: document.body
    mhchem:
      enable: true
  print:
    disable_toc: false
  markmap:
    enable: false

# Language
languageCode: de
defaultContentLanguage: de
defaultContentLanguageInSubdir: false
contentDir: "content/de"
enableMissingTranslationPlaceholders: true

# Menu
menu:
  main:
    - name: GitHub
      weight: 50
      url: "https://github.com/Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung"
      pre: <i class="fab fa-github"></i>

# Outputs
outputs:
  section:
    - HTML
    - RSS
    - print

# SEO
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

enableRobotsTXT: true

# Privacy

privacy:
  # disqus:
  #   disable: false
  # googleAnalytics:
  #   anonymizeIP: false
  #   disable: false
  #   respectDoNotTrack: false
  #   useSessionStorage: false
  # instagram:
  #   disable: false
  #   simple: false
  # twitter:
  #   disable: false
  #   enableDNT: false
  #   simple: false
  # vimeo:
  #   disable: false
  #   enableDNT: false
  #   simple: false
  youtube:
    disable: false
    privacyEnhanced: true