# Basics
baseURL: https://fi.lna-dev.net
title: Fachinformatiker-Prüfungsvorbereitung
theme: github.com/google/docsy
enableGitInfo: true

# Modules
module:
  imports:
  - path: github.com/google/docsy
  - path: github.com/google/docsy/dependencies

# Content
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: tango

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango

params:
  copyright: "The Fachinformatiker-Prüfungsvorbereitung Authors"
  # privacy_policy: "https://policies.google.com/privacy"
  ui:
    readingTime:
      enable: true

  offlineSearch: true
  algolia_docsearch: false
  offlineSearchSummaryLength: 70
  offlineSearchMaxResults: 10
  prism_syntax_highlighting: false

  # GitHub
  github_repo: "https://github.com/LNA-DEV/Fachinformatiker-Anwendungsentwicklung-Pruefungsvorbereitung"
  github_project_repo: "https://github.com/LNA-DEV/Fachinformatiker-Anwendungsentwicklung-Pruefungsvorbereitung"
  github_branch: "dev"

  mermaid:
    enable: true
    theme: default
  plantuml:
    enable: true
    theme: default
    svg_image_url: https://www.plantuml.com/plantuml/svg/
    svg: false
  katex:
    enable: true
    html_dom_element: document.body
    mhchem:
      enable: true
  print:
    disable_toc: false
  markmap:
    enable: true

# Language
languageCode: de
defaultContentLanguage: de
defaultContentLanguageInSubdir: false
contentDir: "content/de"
enableMissingTranslationPlaceholders: true

# Menu
menu:
  main:
    - name: GitHub
      weight: 50
      url: "https://github.com/LNA-DEV/Fachinformatiker-Anwendungsentwicklung-Pruefungsvorbereitung"
      pre: <i class="fa-brands fa-github"></i>

# Outputs
outputs:
  section:
    - HTML
    - RSS
    - print

# SEO
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

enableRobotsTXT: true
